let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual top",
    price: 78,
    desc: "Sassafras Red Pure Cotton Tank Crop Top",
    img: "images/imagee1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Sera Tops",
    price: 100,
    desc: "Mauve Floral Chiffon Regular Crop Top",
    img: "images/imagee2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 105,
    desc: "H&M Orange Cotton T-Shirt.",
    img: "images/imagee3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Midi Dress",
    price: 75,
    desc: "Off White & Green Floral Print Keyhole Neck Ethnic A-Line Midi Dress",
    img: "images/imagee4.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Maxi Dress",
    price: 35,
    desc: "Mustard Yellow & Pink Ethnic Motifs Printed Pure Cotton Anarkali Tiered Maxi Dress",
    img: "images/imagee5.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Kurti",
    price: 150,
    desc: "Women Teal Blue & Beige Ethnic Motifs Printed Straight Kurti.",
    img: "images/imagee6.jpg",
  },
];
